spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: app
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


jwt:
  secret: your-very-long-secret-key-at-least-32-characters-long
  expiration-ms: 86400000

server:
  port: 8085