spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: app
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: com.example.common.event
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8084

jwt:
  secret: your-very-long-secret-key-at-least-32-characters-long